name: Instance Validator

on:
  repository_dispatch:
    types: [instance_validator_trigger]
  push:
    branches:
      - pipeline

jobs:
  validate-instance:
    uses: openMetadataInitiative/openMINDS_actions/.github/workflows/instance_validator.yml@main
