name: Instance Validator

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-instance:
    uses: openMetadataInitiative/openMINDS_actions/.github/workflows/instance_validator.yml@main
