name: openMINDS_upstream

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Autopopulation"]
    types:
      - completed
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - repo: openMetadataInitiative/openMINDS_json-schema
            workflow: build.yml
            inputs: '{"branch":"${{ github.ref_name }}","repository":"${{ github.repository }}"}'

          - repo: openMetadataInitiative/openMINDS_MATLAB
            workflow: build.yml

          - repo: openMetadataInitiative/openMINDS_Python
            workflow: build.yml

          - repo: openMetadataInitiative/openMINDS_Python
            workflow: build-dev.yml

          - repo: openMetadataInitiative/openMINDS_LinkML
            workflow: build.yml
            inputs: '{"branch":"${{ github.ref_name }}","repository":"${{ github.repository }}"}'

          - repo: openMetadataInitiative/openMINDS_documentation
            workflow: build.yml

          - repo: openMetadataInitiative/openMINDS_documentation
            workflow: htaccess-deploy.yml

    steps:
    - name: Trigger target repositories
      run: |
        if [ -n "${{ matrix.inputs }}" ]; then
          DATA='{"ref":"pipeline","inputs":'${{ matrix.inputs }}'}'
        else
          DATA='{"ref":"pipeline"}'
        fi
        
        curl -s -w "\n${{ matrix.repo }}: %{http_code}\n" \
          -X POST \
          -u "${{ secrets.PAT_USERNAME }}:${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/${{ matrix.repo }}/actions/workflows/${{ matrix.workflow }}/dispatches \
          --data "$DATA"
