name: openMINDS_upstream_pr

on:
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger pipeline workflow via repository_dispatch
      run: |
        curl -XPOST -u "${{secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/openMetadataInitiative/openMINDS_instances/actions/workflows/instance_validator.yml/dispatches --data '{"event_type": "instance_validator_trigger"}'
        curl -XPOST -u "${{secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/openMetadataInitiative/openMINDS_instances/actions/workflows/json-ld-validator.yml/dispatches --data '{"event_type": "json-ld-validator_trigger"}'
