name: openMINDS_upstream

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Autopopulation"]
    types:
      - completed
  workflow_dispatch:
  
jobs:
  build:
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - repo: openMetadataInitiative/openMINDS_json-schema
            workflow: build.yml

          - repo: openMetadataInitiative/openMINDS_MATLAB
            workflow: build.yml

          - repo: openMetadataInitiative/openMINDS_Python
            workflow: build.yml

          - repo: openMetadataInitiative/openMINDS_Python-dev
            workflow: build-dev.yml

          - repo: openMetadataInitiative/openMINDS_LinkML
            workflow: build.yml

          - repo: openMetadataInitiative/openMINDS_documentation
            workflow: build.yml

          - repo: openMetadataInitiative/openMINDS_documentation
            workflow: htaccess-deploy.yml

    steps:
    - name: Trigger target repositories
      run: |
          curl -s -w "\n${{ matrix.repo }}: %{http_code}\n" \
            -X POST \
            -u "${{ secrets.PAT_USERNAME }}:${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/${{ matrix.repo }}/actions/workflows/${{ matrix.workflow }}/dispatches \
            --data "{
              \"ref\": \"pipeline\",
              \"inputs\": {
                \"branch\": \"${{ github.ref_name }}\",
                \"repository\": \"${{ github.repository }}\"
              }
            }"
